### ISSUE TITLE
Проверка API

### ISSUE THREAD

**Issue by vi-dev0** [b4dcat404/Trello-TG-bot#1]
Сделать проверку на верные ключи API

Возможно: 
If статус ответа 200
 Ок
Else
 Установить ключи заново

Как то так должно сработать
Кроме проверки на ответ 200 опций нет, ибо других ответов API не даёт

**Comment by b4dcat404** [comment]
Реализовал проверкой ответа 

if response == 200:
    asd
else:
   Неверные данные
